config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :subscribers, only: [ :create ]
  end
  resource :unsubscribe, only: [ :show ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/product/notifications.rb
module Product::Notifications
  extend ActiveSupport::Concern

  included do
    has_many :subscribers, dependent: :destroy
    after_update_commit :notify_subscribers, if: :back_in_stock?
  end

  def back_in_stock?
    inventory_count_previously_was == 0 && inventory_count > 0
  end

  def notify_subscribers
    subscribers.each do |subscriber|
      ProductMailer.with(product: self, subscriber: subscriber).in_stock.deliver_later
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Notifications
  has_one_attached :featured_image
  has_rich_text :description
  has_many :subscribers, dependent: :destroy

  validates :name, presence: true
  validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :product
  generates_token_for :unsubscribe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.expect(product: [ :name, :description, :featured_image, :inventory_count ])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  allow_unauthenticated_access
  before_action :set_product

  def create
    @product.subscribers.where(subscriber_params).first_or_create
    redirect_to @product, notice: "You are now subscribed."
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def subscriber_params
    params.expect(subscriber: [ :email ])
  end
end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController
  allow_unauthenticated_access
  before_action :set_subscriber

  def show
    @subscriber&.destroy
    redirect_to root_path, notice: "Unsubscribed successfully."
  end

  private

  def set_subscriber
    @subscriber = Subscriber.find_by_token_for(:unsubscribe, params[:token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/unsubscribes_helper.rb
module UnsubscribesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-controller="color-scheme">
  <head>
    <title><%= content_for(:title) || "Store Okkio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "css-zero/reset", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "css-zero/variables", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "css-zero/utilities", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="header-layout">
  

    <header id="header">
      <div contents data-controller="popover" data-popover-placement-value="bottom-start">
        <button type="button" class="btn btn--icon" data-popover-target="trigger" popovertarget="color_scheme_popover" aria-haspopup="true">
          <span class="icon icon--sun icon--color-scheme-light" aria-hidden="true"></span>
          <span class="icon icon--moon icon--color-scheme-dark" aria-hidden="true"></span>
          <span class="sr-only">Theme switcher</span>
        </button>
        <div popover id="color_scheme_popover" class="popover" data-popover-target="content" role="menu" aria-label="Menu">
          <div class="menu" data-controller="menu" data-action="keydown->menu#navigate">
            <button type="button" class="btn menu__item" data-action="popover#hide color-scheme#setLight" data-menu-target="item" role="menuitem">Light</button>
            <button type="button" class="btn menu__item" data-action="popover#hide color-scheme#setDark" data-menu-target="item" role="menuitem">Dark</button>
            <button type="button" class="btn menu__item" data-action="popover#hide color-scheme#setSystem" data-menu-target="item" role="menuitem">System</button>
          </div>
        </div>
      </div>
      <div class="flex justify-between container">
        <div class="flex items-center gap">
          <%= image_tag "/icon.svg", alt: "Store Okkio", width: "32", height: "32" %>
          <%= link_to root_path do %>
            <h1>Store Okkio</h1>
          <% end %>
        </div>
      <nav class="flex gap ">
        <%= button_to "Log out", session_path, method: :delete if authenticated? %>
      </nav>
      </div>
    </header>

    <main id="main">
      <% if notice.present? %>
        <div popover class="flash" style="--flash-position: 5rem;" data-controller="element-removal" data-action="animationend->element-removal#remove" role="alert"><%= notice %></div>
      <% end %>
      <div class="notice"><%= notice %></div>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product, class: "flex flex-col gap-6 p-6 rounded-lg " do |f| %>

  
  <header class="flex flex-col gap-1 mb-4">
    <h2 class="text-2xl font-bold text-primary">Produto</h2>
    <p class="text-sm text-subtle">Preencha os campos abaixo para adicionar seu produto à loja.</p>
  </header>

  <div>
    <%= f.label :featured_image, style: "display: block" %>
    <%= f.file_field :featured_image, accept: "image/*" %>
  </div>

  
  <div class="flex flex-col gap-4">
    <div class="flex flex-col gap-1">
      <%= f.label :name, "Nome do Produto", class: "text-sm font-medium" %>
      <%= f.text_field :name, placeholder: "Ex: Camiseta Retrô Azul", class: "input" %>
    </div>

    <div class="flex flex-col gap-1">
      <%= f.label :description, "Descrição", class: "text-sm font-medium" %>
      <%= f.rich_text_area :description, class: "input", placeholder: "Descreva seu produto com detalhes." %>
    </div>

    <div class="flex flex-col gap-1">
      <%= f.label :inventory_count %>
      <%= f.number_field :inventory_count, class: "input", placeholder: "Quantidade em estoque."%>
    </div>
  </div>

  
  <div class="flex items-center justify-between mt-6">
    <%= link_to "Cancelar", products_path, class: "btn btn--secondary" %>
    <%= f.submit "Salvar produto", class: "btn btn--primary" %>
  </div>

<% end %>

app/views/products/_inventory.html.erb
<% if product.inventory_count? %>
  <p><%= product.inventory_count %> in stock</p>
<% else %>
  <p>Out of stock</p>
  <p>Email me when available.</p>

  <%= form_with model: [product, Subscriber.new] do |form| %>
    <%= form.email_field :email, placeholder: "you@example.com", required: true %>
    <%= form.submit "Submit" %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="flex flex-col rounded-lg">
  <div class="flex items-center justify-between p-4 border-be">
    <h1 class="text-xl font-bold"><%= t ".title" %></h1>
    <% if authenticated? %>
      <%= link_to "New product", new_product_path, class: "btn btn--positive" %>
    <% end %>
  </div>
  
  <div id="products" class="flex flex-wrap gap p-2 justify-center">
    <% @products.each do |product| %>
      <div class="card p-4 text-center rounded-md shadow-sm border bg-main" style="width: 300px;">
        <% if product.featured_image.attached? %>
          <%= image_tag product.featured_image.variant(resize_to_fill: [300, 200]),
                        class: "rounded-md w-full h-48 object-cover" %>
        <% end %>
        <h2 class="text-lg font-bold text-primary">
          <%= link_to product.name, product, class: "link" %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="flex flex-col gap-half p-6 rounded-md bg-main">
  <div class="flex flex-col md:flex-row gap-6 items-start">

    <% if @product.featured_image.attached? %>
      <div class="flex-shrink-0 w-full md:w-1/3">
        <%= image_tag @product.featured_image.variant(resize_to_fill: [600, 300]),
                      class: "rounded-md w-full object-cover border border-main" %>
      </div>
    <% end %>

    <div class="flex flex-col gap-4 w-full">
      <h1 class="text-3xl font-bold text-primary"><%= @product.name %></h1>
      <p class="text-base text-subtle leading-tight"><%= @product.description %></p>
      <%= render "inventory", product: @product %>
    </div>
  </div>

  <div class="flex gap-3 items-center flex-wrap">

    <%= link_to products_path, class: "btn btn--primary", title: "Voltar para produtos" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="lucide lucide-arrow-big-left" width="20" height="20" viewBox="0 0 24 24" stroke="currentColor" fill="none"><path d="M18 15h-6v4l-7-7 7-7v4h6v6z"/></svg>
      <span class="mis-2">Voltar</span>
    <% end %>

    <% if authenticated? %>
      <%= link_to edit_product_path(@product), class: "btn", title: "Editar produto" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="lucide lucide-square-pen" width="20" height="20" viewBox="0 0 24 24" stroke="currentColor" fill="none"><path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"/></svg>
        <span class="mis-2">Editar</span>
      <% end %>

      <%= button_to @product, method: :delete, data: { turbo_confirm: "Tem certeza que deseja excluir este produto?" }, class: "btn btn--negative", title: "Excluir produto" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="lucide lucide-trash-2" width="20" height="20" viewBox="0 0 24 24" stroke="currentColor" fill="none"><path d="M10 11v6"/><path d="M14 11v6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
        <span class="mis-2">Excluir</span>
      <% end %>
    <% end %>

  </div>
</div>